[package]
name = "rag-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rag"
path = "src/main.rs"

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-http-client.workspace = true
chrono = { version = "0.4", default-features = false, features = ["std"] }
clap.workspace = true
md-5.workspace = true
hyper-rustls.workspace = true
parquet.workspace = true
rag-embedding.workspace = true
rag-index.workspace = true
rag-ocsf.workspace = true
rag-pipeline.workspace = true
rag-projection.workspace = true
rayon.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
